#!/usr/bin/env bash

apt update
apt install -y curl

curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && \
    chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null

apt-add-repository ppa:wslutilities/wslu
apt-add-repository ppa:fish-shell/release-3
apt update

apt install -y \
    fish \
    gh \
    git-delta \
    make \
    python3 \
    python3-pip \
    python3-setuptools \
    ripgrep \
    unzip \
    wslu
