#!/usr/bin/env bash

apt-add-repository ppa:wslutilities/wslu
apt-add-repository ppa:fish-shell/release-3

apt update

apt install -y \
    curl \
    fish \
    make \
    python3 \
    python3-pip \
    python3-setuptools \
    unzip \
    wslu
